
# Tap.
- name: Ensure configured taps are tapped.
  community.general.homebrew_tap:
    tap: '{{ item.name | default(item) }}'
    url: '{{ item.url | default(omit) }}'
    state: present
  loop: "{{ homebrew_taps }}"
  tags: homebrew

# Brew.
- name: Ensure configured homebrew packages are installed ( This step will take a while depending on number of brews to install )
  community.general.homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop: "{{ homebrew_installed_packages }}"
  tags: homebrew

- name: Upgrade all homebrew packages (if configured).
  community.general.homebrew: 
    update_homebrew: yes
    upgrade_all: yes
  when: homebrew_upgrade_all_packages
  tags: homebrew

# Cask.
- name: Install configured cask applications.
  community.general.homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: present
    install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
  loop: "{{ homebrew_cask_apps }}"
  tags: homebrew

- name: Check for Brewfile.
  stat:
    path: "{{ homebrew_brewfile_dir }}/Brewfile"
  register: homebrew_brewfile
  tags: homebrew

- name: Install from Brewfile.
  command: "brew bundle"
  args:
    chdir: "{{ homebrew_brewfile_dir }}"
  when: homebrew_brewfile.stat.exists and homebrew_use_brewfile
  tags: homebrew
